// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillTest.Infrastructure.Persistence;

#nullable disable

namespace SkillTest.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkillTest.Domain.TestAttempts.Entities.TestAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TestAttempts", (string)null);
                });

            modelBuilder.Entity("SkillTest.Domain.TestAttempts.Entities.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.ToTable("TestResults", (string)null);
                });

            modelBuilder.Entity("SkillTest.Domain.TestAttempts.Entities.TestResultAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<int>("EarnedPoints")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("TestResultAnswers", (string)null);
                });

            modelBuilder.Entity("SkillTest.Domain.Tests.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers", (string)null);
                });

            modelBuilder.Entity("SkillTest.Domain.Tests.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8d9f3b2-7c44-4c1e-9f0a-2e6b1d9a8f55"),
                            Color = "#FF5733",
                            Description = "All programming-related topics",
                            Icon = "code",
                            Name = "Programming"
                        },
                        new
                        {
                            Id = new Guid("c1e7a2d4-9b33-4f0d-8c77-1a2b3c4d5e66"),
                            Color = "#33A1FF",
                            Description = "Network technologies and protocols",
                            Icon = "network",
                            Name = "Networking"
                        },
                        new
                        {
                            Id = new Guid("5b9e1f22-3c8d-4f7a-9d11-7c8e2a1b4f99"),
                            Color = "#33FF57",
                            Description = "CI/CD, automation, infrastructure",
                            Icon = "devops",
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = new Guid("d4a1c7e8-2b55-4f33-8e0c-9a1d2b3c4e77"),
                            Color = "#FF33A8",
                            Description = "SQL, NoSQL, data modeling",
                            Icon = "database",
                            Name = "Databases"
                        },
                        new
                        {
                            Id = new Guid("9c7a4e11-2d3f-4b8a-9f55-6e7d8c9b1a44"),
                            Color = "#FFC300",
                            Description = "Frontend, backend, web technologies",
                            Icon = "web",
                            Name = "Web Development"
                        });
                });

            modelBuilder.Entity("SkillTest.Domain.Tests.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("SkillTest.Domain.Tests.Entities.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tests", (string)null);
                });

            modelBuilder.Entity("SkillTest.Domain.Users.Entities.PointTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PointTransactions", (string)null);
                });

            modelBuilder.Entity("SkillTest.Domain.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f4c2c8c-1c0e-4e4e-9b8e-0f7a4b6d2c11"),
                            TotalPoints = 0
                        });
                });

            modelBuilder.Entity("SkillTest.Domain.TestAttempts.Entities.TestResult", b =>
                {
                    b.HasOne("SkillTest.Domain.TestAttempts.Entities.TestAttempt", null)
                        .WithMany("Results")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillTest.Domain.TestAttempts.Entities.TestResultAnswer", b =>
                {
                    b.HasOne("SkillTest.Domain.TestAttempts.Entities.TestResult", null)
                        .WithMany("Answers")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillTest.Domain.Tests.Entities.Answer", b =>
                {
                    b.HasOne("SkillTest.Domain.Tests.Entities.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SkillTest.Domain.Tests.Entities.Question", b =>
                {
                    b.HasOne("SkillTest.Domain.Tests.Entities.Test", null)
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsMany("SkillTest.Domain.Tests.ValueObjects.Shared.Tag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("QuestionId");

                            b1.ToTable("QuestionTags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("QuestionId");
                        });

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("SkillTest.Domain.Tests.Entities.Test", b =>
                {
                    b.HasOne("SkillTest.Domain.Tests.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("SkillTest.Domain.Tests.ValueObjects.Shared.Tag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("TestId");

                            b1.ToTable("TestTags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TestId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("SkillTest.Domain.Users.Entities.PointTransaction", b =>
                {
                    b.HasOne("SkillTest.Domain.Users.Entities.User", null)
                        .WithMany("PointTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillTest.Domain.Users.Entities.User", b =>
                {
                    b.OwnsOne("SkillTest.Domain.Users.ValueObjects.User.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.HasData(
                                new
                                {
                                    UserId = new Guid("3f4c2c8c-1c0e-4e4e-9b8e-0f7a4b6d2c11"),
                                    Value = "admin@example.com"
                                });
                        });

                    b.OwnsOne("SkillTest.Domain.Users.ValueObjects.User.UserProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AvatarUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("AvatarUrl");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Position");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("SkillTest.Domain.Users.ValueObjects.User.FullName", "FullName", b2 =>
                                {
                                    b2.Property<Guid>("UserProfileUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("FirstName");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("LastName");

                                    b2.HasKey("UserProfileUserId");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserProfileUserId");

                                    b2.HasData(
                                        new
                                        {
                                            UserProfileUserId = new Guid("3f4c2c8c-1c0e-4e4e-9b8e-0f7a4b6d2c11"),
                                            FirstName = "Admin",
                                            LastName = "Admin"
                                        });
                                });

                            b1.OwnsOne("SkillTest.Domain.Users.ValueObjects.User.Username", "Username", b2 =>
                                {
                                    b2.Property<Guid>("UserProfileUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Username");

                                    b2.HasKey("UserProfileUserId");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserProfileUserId");

                                    b2.HasData(
                                        new
                                        {
                                            UserProfileUserId = new Guid("3f4c2c8c-1c0e-4e4e-9b8e-0f7a4b6d2c11"),
                                            Value = "admin"
                                        });
                                });

                            b1.Navigation("FullName")
                                .IsRequired();

                            b1.Navigation("Username")
                                .IsRequired();

                            b1.HasData(
                                new
                                {
                                    UserId = new Guid("3f4c2c8c-1c0e-4e4e-9b8e-0f7a4b6d2c11"),
                                    AvatarUrl = "",
                                    Position = "Administrator"
                                });
                        });

                    b.OwnsOne("UserSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AutoAdvanceEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("AutoAdvanceEnabled");

                            b1.Property<bool>("EmailNotificationsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("EmailNotificationsEnabled");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("Language");

                            b1.Property<int?>("TimeLimitSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("TimeLimitSeconds");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.HasData(
                                new
                                {
                                    UserId = new Guid("3f4c2c8c-1c0e-4e4e-9b8e-0f7a4b6d2c11"),
                                    AutoAdvanceEnabled = false,
                                    EmailNotificationsEnabled = true,
                                    Language = "ru",
                                    TimeLimitSeconds = 0
                                });
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillTest.Domain.TestAttempts.Entities.TestAttempt", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("SkillTest.Domain.TestAttempts.Entities.TestResult", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("SkillTest.Domain.Tests.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("SkillTest.Domain.Tests.Entities.Test", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SkillTest.Domain.Users.Entities.User", b =>
                {
                    b.Navigation("PointTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
